serverless-validate.yaml
stetind/ppc-reusable-workflows pull request #28
Opened 2024-10-18 14:01 UTC by StfRoula

2024-10-21 07:08 UTC, andreas-kondylis-eli requested changes

2024-10-21 07:08 UTC, andreas-kondylis-eli commented on .github/workflows/serverless-validate.yaml
Please check it again, and verify the process, 
I believe that the script will throw error.

2024-10-31 13:41 UTC, andreas-kondylis-eli approved these changes

2024-10-31 13:54 UTC, nmemos submitted a review, later dismissed

2024-11-01 11:00 UTC, merged